DROP DATABASE IF EXISTS login;
CREATE DATABASE login;

USE login;

CREATE TABLE Usuario (
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  usuario NVARCHAR(20) NOT NULL,
  contra NVARCHAR(20) NOT NULL,
  cargo NVARCHAR(20) NOT NULL
);

ALTER TABLE Usuario MODIFY COLUMN usuario VARCHAR(50);
ALTER TABLE Usuario MODIFY COLUMN contra VARCHAR(100);

DESCRIBE Usuario;